<?php

namespace Synapse\Cmf\Framework\Media\Video\Entity;

use Synapse\Cmf\Framework\Media\Video\Model\VideoInterface;
use Majora\Framework\Model\CollectionableTrait;
use Majora\Framework\Model\TimedTrait;
use Majora\Framework\Normalizer\Model\NormalizableTrait;

/**
 * Video entity class.
 */
class Video implements VideoInterface
{
    use CollectionableTrait, NormalizableTrait, TimedTrait;

    /**
     * @var int
     */
    protected $id;

    /**
     * @see NormalizableInterface::getScopes()
     */
    public static function getScopes()
    {
        return array(
            'id' => 'id',
            'default' => array('id'),
        );
    }

    /**
     * Returns Video id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Define Video id.
     *
     * @param int $id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    // *************************************************

    // Class auto generated by MajoraGeneratorBundle
    // Implement your own logic here !

    // *************************************************
}
