# Doctrine
doctrine:
    orm:
        entity_managers:
            synapse:
                mappings:
                    SynapseCmfBundle:
                        type: yml
                        dir: Resources/config/mapping/orm
                        prefix: Synapse\Cmf\Bundle\Entity\Orm
                        alias: Synapse
                    SynapsePageBundle:
                        type: yml
                        dir: Resources/config/mapping/orm
                        prefix: Synapse\Page\Bundle\Entity
                        alias: SynapsePage

# Doctrine behaviors
stof_doctrine_extensions:
    orm:
        synapse:
            timestampable: true
            tree: true

# Synapse Content Type
synapse_cmf:
    content_types:
        Synapse\Page\Bundle\Entity\Page:
            alias: page
            provider: synapse.page.loader
    components:
        page_menu:
            form: 'Synapse\Page\Bundle\Form\PageMenu\PageMenuType'
            controller: SynapsePageBundle:PageMenuContent:render
            template_path: "SynapsePageBundle:Admin/PageMenu:page_menu.html.twig"

synapse_admin:
    base_layout: "SynapsePageBundle::base.html.twig"
